### ISSUE TITLE
其他问题

### ISSUE THREAD

**Issue by Gaoyifei1011** [nuscien/winkit#1]
之前关注到您开发了爱奇艺Winui3的版本，并提交到了Microsoft Store商店，感觉您开发的应用非常棒。在使用过程中发现部分页面使用了webview2控件，在页面发生跳转时，如果跳转到没有webview2页面的控件时，可以清晰的从任务管理器中看到webview2进程被杀死了，想问一下您这一过程是如何实现的，有相应的API文档吗？

**Comment by kingcean** [comment]
可以直接调用该 WebView2 实例的 Close() 成员方法来结束对应进程。这么做的另一个好处是，如果当前页面嵌入并运行着 WebView2，及时调用该方法可以降低关闭该应用时，可能偶尔产生的异常（虽然由此产生的崩溃并不会给用户带来明显感觉）。

另外，如果你发现 WebView2 有什么显著问题，也可以反馈给我，我们（指微软）都会去尝试解决的。

**Comment by Gaoyifei1011** [comment]
非常感谢，您热心的回复的确解决了我的疑惑。如果在使用的过程中遇到问题，我会联系您的，谢谢。
